export const FETCH_RECIPES = 'FETCH_RECIPES';

export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';

export const GET_RECIPES = 'GET_RECIPES';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';

export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const INITIALIZE_INGREDIENTS = 'INITIALIZE_INGREDIENTS';


