module.exports = {
    "protein": [{
            "recipe": { "id": 1, "name": "P: Deonte", "imageURL": null, "multiplier": 2, "vegetarian": false, "BLD": "d", "difficulty": 2 },
            "ingredients": [{ "id": 1, "name": "P_I:P: Deonte", "vegetarian": false, "staple": true, "proteinRecipeId": 1 }, { "id": 2, "name": "P_I:P: Deonte", "vegetarian": false, "staple": false, "proteinRecipeId": 1 }, { "id": 3, "name": "P_I:P: Deonte", "vegetarian": true, "staple": true, "proteinRecipeId": 1 }],
            "instructions": [{ "id": 1, "name": "P: Deonte", "stepId": 0, "step": "Quam numquam quaerat ad qui. Vero sint quae ducimus fugiat. Placeat nobis atque aspernatur deserunt.", "proteinRecipeId": 1 }, { "id": 2, "name": "P: Deonte", "stepId": 1, "step": "Eveniet tempore est id laboriosam fuga. Eum sapiente ut minus eaque.", "proteinRecipeId": 1 }, { "id": 3, "name": "P: Deonte", "stepId": 2, "step": "Et perspiciatis porro sapiente aut cumque inventore tempora dolores ut. Vero rerum repellendus odit velit debitis modi quaerat consequatur.", "proteinRecipeId": 1 }]
        },
        {
            "recipe": { "id": 2, "name": "P: Shemar", "imageURL": null, "multiplier": 2, "vegetarian": true, "BLD": "d", "difficulty": 3 },
            "ingredients": [{ "id": 4, "name": "P_I:P: Shemar", "vegetarian": true, "staple": true, "proteinRecipeId": 2 }, { "id": 5, "name": "P_I:P: Shemar", "vegetarian": false, "staple": false, "proteinRecipeId": 2 }, { "id": 6, "name": "P_I:P: Shemar", "vegetarian": true, "staple": false, "proteinRecipeId": 2 }],
            "instructions": [{ "id": 4, "name": "P: Shemar", "stepId": 0, "step": "Voluptatibus enim sit vero est. Unde incidunt quis enim saepe eum molestias dolorum quisquam. Quaerat temporibus omnis consequatur. Doloribus error ullam quia incidunt sapiente fuga.", "proteinRecipeId": 2 }, { "id": 5, "name": "P: Shemar", "stepId": 1, "step": "Quia eveniet tempora. Et eos dolores deserunt sed consequuntur modi libero id minima. Pariatur totam velit quas. Id aut unde est commodi ad et id velit asperiores. Dignissimos necessitatibus et ullam omnis nisi vel.", "proteinRecipeId": 2 }, { "id": 6, "name": "P: Shemar", "stepId": 2, "step": "Earum ullam est suscipit itaque repellat minus dolores est accusamus. Quia aliquid in. Reprehenderit reiciendis qui quisquam corrupti similique esse maxime aspernatur.", "proteinRecipeId": 2 }]
        },
        {
            "recipe": { "id": 3, "name": "P: Reilly", "imageURL": null, "multiplier": 4, "vegetarian": true, "BLD": "d", "difficulty": 2 },
            "ingredients": [{ "id": 7, "name": "P_I:P: Reilly", "vegetarian": true, "staple": false, "proteinRecipeId": 3 }, { "id": 8, "name": "P_I:P: Reilly", "vegetarian": true, "staple": true, "proteinRecipeId": 3 }, { "id": 9, "name": "P_I:P: Reilly", "vegetarian": false, "staple": false, "proteinRecipeId": 3 }],
            "instructions": [{ "id": 7, "name": "P: Reilly", "stepId": 0, "step": "Voluptatibus eius eligendi. Deserunt quos sequi. Earum et ex quas sed.", "proteinRecipeId": 3 }, { "id": 8, "name": "P: Reilly", "stepId": 1, "step": "Ut praesentium voluptatem natus dignissimos at sed corporis saepe praesentium. Aut quam quod maxime voluptatem distinctio adipisci quia labore. Ducimus dignissimos nihil nihil est nesciunt totam quibusdam.", "proteinRecipeId": 3 }, { "id": 9, "name": "P: Reilly", "stepId": 2, "step": "Omnis qui harum ipsum quo qui adipisci. Id perferendis aliquid maxime architecto. Aut provident earum sed blanditiis fugiat ad eaque. Ipsam eos dicta neque eos nisi et illum. Cumque quis corporis.", "proteinRecipeId": 3 }]
        }
    ],
    "vegetables": [{
            "recipe": { "id": 1, "name": "V:Keegan", "imageURL": null, "multiplier": 1, "vegetarian": true, "BLD": "b", "difficulty": 3 },
            "ingredients": [{ "id": 19, "name": "IF:V:Keegan", "vegetarian": true, "staple": false, "vegetableRecipeId": 1 }, { "id": 20, "name": "IF:V:Keegan", "vegetarian": true, "staple": false, "vegetableRecipeId": 1 }, { "id": 21, "name": "IF:V:Keegan", "vegetarian": true, "staple": true, "vegetableRecipeId": 1 }],
            "instructions": [{ "id": 19, "name": "V:Keegan", "stepId": 0, "step": "Est minima ratione distinctio. Quaerat illum minima dignissimos repellendus et. In repellendus rerum non amet libero in vel. Aliquam autem voluptas quo rerum vero ut.", "vegetableRecipeId": 1 }, { "id": 20, "name": "V:Keegan", "stepId": 1, "step": "Dolores dignissimos voluptatum quia quaerat. Asperiores similique enim. Nobis delectus harum. Est eos cumque quasi rerum. Dolor exercitationem natus vero iusto dolores a.", "vegetableRecipeId": 1 }, { "id": 21, "name": "V:Keegan", "stepId": 2, "step": "Fugit et ut voluptates quo esse. Culpa aut eaque voluptatem repellendus quisquam eum ut possimus. Ex expedita aut. Similique rerum et. Dolores quas aliquam maiores. Quia perspiciatis ex voluptatum aut molestiae dicta laborum iste iste.", "vegetableRecipeId": 1 }]
        },
        {
            "recipe": { "id": 2, "name": "V:Jeanie", "imageURL": null, "multiplier": 1, "vegetarian": true, "BLD": "b", "difficulty": 2 },
            "ingredients": [{ "id": 25, "name": "IF:V:Jeanie", "vegetarian": true, "staple": false, "vegetableRecipeId": 2 }, { "id": 26, "name": "IF:V:Jeanie", "vegetarian": true, "staple": true, "vegetableRecipeId": 2 }, { "id": 27, "name": "IF:V:Jeanie", "vegetarian": true, "staple": true, "vegetableRecipeId": 2 }],
            "instructions": [{ "id": 25, "name": "V:Jeanie", "stepId": 0, "step": "At soluta tempore a. Omnis rerum voluptatem. Sapiente quisquam quo ut et. Illo totam optio commodi reprehenderit quis facilis quia nihil accusamus. Accusamus dolorem ea sunt est consectetur dolor.", "vegetableRecipeId": 2 }, { "id": 26, "name": "V:Jeanie", "stepId": 1, "step": "Officiis quis doloremque labore vitae. Ut id distinctio est id error. Ut voluptatibus nobis doloremque veritatis id illum sed vel. Odio aut ut ut. Dignissimos ut sunt nisi reiciendis debitis. In non quod qui tenetur maiores.", "vegetableRecipeId": 2 }, { "id": 27, "name": "V:Jeanie", "stepId": 2, "step": "Voluptatem architecto nobis a accusantium quod asperiores quia. Dolores modi ipsam aut. Id commodi unde cupiditate at amet pariatur laborum.", "vegetableRecipeId": 2 }]
        },
        {
            "recipe": { "id": 3, "name": "V:Kip", "imageURL": null, "multiplier": 2, "vegetarian": true, "BLD": "b", "difficulty": 3 },
            "ingredients": [{ "id": 22, "name": "IF:V:Kip", "vegetarian": true, "staple": true, "vegetableRecipeId": 3 }, { "id": 23, "name": "IF:V:Kip", "vegetarian": true, "staple": false, "vegetableRecipeId": 3 }, { "id": 24, "name": "IF:V:Kip", "vegetarian": true, "staple": false, "vegetableRecipeId": 3 }],
            "instructions": [{ "id": 22, "name": "V:Kip", "stepId": 0, "step": "Saepe quos animi fugiat quo. Ut ea tenetur quia. Eos temporibus dolores perspiciatis. Ut qui quisquam sed autem fuga ratione. Magnam praesentium at eum accusantium asperiores. Assumenda eum voluptatem iste quod.", "vegetableRecipeId": 3 }, { "id": 23, "name": "V:Kip", "stepId": 1, "step": "Amet eos quia tempore commodi nisi quia. Doloremque quam aut delectus harum voluptatibus. Nihil expedita perspiciatis quo iure qui deserunt. Quod et ut commodi dolorem aut eveniet. Quibusdam architecto qui est pariatur.", "vegetableRecipeId": 3 }, { "id": 24, "name": "V:Kip", "stepId": 2, "step": "Numquam voluptatibus quia est sit distinctio dolorum enim. Alias quo atque deserunt in. Asperiores necessitatibus asperiores sit minus quibusdam esse nesciunt. Aut ratione incidunt fuga in odio veniam. Omnis sed voluptas tempore atque non velit perspiciatis illum aut. Qui ducimus corporis omnis qui sint aliquam accusamus quis.", "vegetableRecipeId": 3 }]
        }
    ],
    "carbs": [{
            "recipe": { "id": 1, "name": "C:Lucious", "imageURL": null, "multiplier": 3, "vegetarian": true, "BLD": "l", "difficulty": 1 },
            "ingredients": [{ "id": 10, "name": "IF:C:Lucious", "vegetarian": true, "staple": true, "carbRecipeId": 1 }, { "id": 11, "name": "IF:C:Lucious", "vegetarian": true, "staple": false, "carbRecipeId": 1 }, { "id": 12, "name": "IF:C:Lucious", "vegetarian": true, "staple": true, "carbRecipeId": 1 }],
            "instructions": [{ "id": 10, "name": "C:Lucious", "stepId": 0, "step": "Dignissimos alias molestiae perspiciatis. Officia temporibus molestias suscipit ratione dolor consectetur. Quasi corrupti illum. Qui ut et blanditiis dolores similique. Dolores veritatis id ut dolore in. Atque aliquam ex rerum id nihil sint.", "carbRecipeId": 1 }, { "id": 11, "name": "C:Lucious", "stepId": 1, "step": "Rerum quia quis. Quaerat cupiditate fugiat ut qui. Voluptatibus eos deserunt autem facilis maiores. Aperiam sunt ullam quae dolorem. In quae ratione aut rerum neque nihil id perferendis exercitationem. Recusandae incidunt vel repudiandae quaerat reprehenderit quia ut.", "carbRecipeId": 1 }, { "id": 12, "name": "C:Lucious", "stepId": 2, "step": "Veritatis assumenda vel. Natus hic repellendus exercitationem aperiam numquam. Sed officia omnis sint in aperiam reprehenderit. Qui occaecati qui consequatur nulla. Exercitationem adipisci recusandae placeat iste repudiandae earum. Quia enim et alias et aut a ducimus.", "carbRecipeId": 1 }]
        },
        {
            "recipe": { "id": 2, "name": "C:Bobbie", "imageURL": null, "multiplier": 3, "vegetarian": true, "BLD": "l", "difficulty": 3 },
            "ingredients": [{ "id": 16, "name": "IF:C:Bobbie", "vegetarian": false, "staple": false, "carbRecipeId": 2 }, { "id": 17, "name": "IF:C:Bobbie", "vegetarian": false, "staple": false, "carbRecipeId": 2 }, { "id": 18, "name": "IF:C:Bobbie", "vegetarian": false, "staple": true, "carbRecipeId": 2 }],
            "instructions": [{ "id": 16, "name": "C:Bobbie", "stepId": 0, "step": "Repudiandae consequatur doloremque consequatur. Qui sunt doloribus accusamus dolorem et labore. Facilis aut aspernatur qui corrupti sequi.", "carbRecipeId": 2 }, { "id": 17, "name": "C:Bobbie", "stepId": 1, "step": "Sint et quasi omnis. Ullam quia totam quos id nemo quia veritatis officiis dolor. Qui excepturi quisquam molestiae nihil veritatis ea vitae.", "carbRecipeId": 2 }, { "id": 18, "name": "C:Bobbie", "stepId": 2, "step": "Nobis vitae quo quis commodi omnis dolor at alias. Corporis natus non modi nulla neque veritatis. Nulla omnis et voluptatem sed sint maiores aut veritatis non. Aut vel harum. Soluta eligendi iste. Rerum quibusdam illum rem voluptatem nemo nobis omnis.", "carbRecipeId": 2 }]
        },
        {
            "recipe": { "id": 3, "name": "C:Cooper", "imageURL": null, "multiplier": 3, "vegetarian": true, "BLD": "l", "difficulty": 3 },
            "ingredients": [{ "id": 13, "name": "IF:C:Cooper", "vegetarian": false, "staple": true, "carbRecipeId": 3 }, { "id": 14, "name": "IF:C:Cooper", "vegetarian": true, "staple": true, "carbRecipeId": 3 }, { "id": 15, "name": "IF:C:Cooper", "vegetarian": false, "staple": true, "carbRecipeId": 3 }],
            "instructions": [{ "id": 13, "name": "C:Cooper", "stepId": 0, "step": "Expedita hic quae sint odio dolorem quia. Eveniet iste repudiandae aperiam et blanditiis officia. Molestias quasi cupiditate deleniti dolores sit omnis adipisci modi. Et ratione sed. Omnis et laborum aut est dolorum doloremque quo odio. Dolorum esse expedita quibusdam cum sunt odit est.", "carbRecipeId": 3 }, { "id": 14, "name": "C:Cooper", "stepId": 1, "step": "Voluptates enim sint. Voluptatem molestiae error laborum repellendus quia dolor.", "carbRecipeId": 3 }, { "id": 15, "name": "C:Cooper", "stepId": 2, "step": "Ratione recusandae quasi et quod asperiores quibusdam aut nihil. Enim unde sint quis nulla. A non et consequatur ut et. Cumque nostrum repellendus commodi quia numquam pariatur rerum dolor quaerat. Voluptate earum sint deleniti sunt blanditiis. Excepturi doloribus eos atque.", "carbRecipeId": 3 }]
        }
    ]
};